# Generated by Django 5.0.2 on 2024-02-10 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinemaPlus", "0004_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="genres",
            new_name="genre",
        ),
    ]
