# Generated by Django 5.0.2 on 2024-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemaPlus", "0005_rename_genres_movie_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
