# Generated by Django 5.0.2 on 2024-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemaPlus", "0006_alter_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="imdb_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
